package com.superdextor.dextersnether.init;

import com.superdextor.dextersnether.DextersNether;
import com.superdextor.dextersnether.blocks.BlockAbyssPortal;
import com.superdextor.dextersnether.blocks.BlockAcid;
import com.superdextor.dextersnether.blocks.BlockCurse;
import com.superdextor.dextersnether.blocks.BlockDarkFire;
import com.superdextor.dextersnether.blocks.BlockDarkSand;
import com.superdextor.dextersnether.blocks.BlockDarkstone;
import com.superdextor.dextersnether.blocks.BlockDimstone;
import com.superdextor.dextersnether.blocks.BlockGhost;
import com.superdextor.dextersnether.blocks.BlockGlowstoneTorch;
import com.superdextor.dextersnether.blocks.BlockHellDoor;
import com.superdextor.dextersnether.blocks.BlockHellFenceGate;
import com.superdextor.dextersnether.blocks.BlockHellPressurePlate;
import com.superdextor.dextersnether.blocks.BlockHugeNetherMushroom;
import com.superdextor.dextersnether.blocks.BlockNetherAltar;
import com.superdextor.dextersnether.blocks.BlockNetherCraftingTable;
import com.superdextor.dextersnether.blocks.BlockNetherFurnace;
import com.superdextor.dextersnether.blocks.BlockNetherLeaves;
import com.superdextor.dextersnether.blocks.BlockNetherLog;
import com.superdextor.dextersnether.blocks.BlockNetherMushroom;
import com.superdextor.dextersnether.blocks.BlockNetherSapling;
import com.superdextor.dextersnether.blocks.BlockSoulGlass;
import com.superdextor.dextersnether.blocks.BlockSoulPane;
import com.superdextor.dextersnether.blocks.BlockSoulTNT;
import com.superdextor.dextersnether.blocks.BlockSpikes;
import com.superdextor.dextersnether.blocks.BlockWitherBlock;
import com.superdextor.thinkbigcore.ModHelper;
import com.superdextor.thinkbigcore.blocks.BlockCustom;
import com.superdextor.thinkbigcore.blocks.BlockCustomOre;
import com.superdextor.thinkbigcore.blocks.BlockCustomPane;
import com.superdextor.thinkbigcore.blocks.BlockCustomSlab;
import com.superdextor.thinkbigcore.blocks.BlockCustomStairs;
import com.superdextor.thinkbigcore.blocks.BlockCustomTrapDoor;
import net.minecraft.block.Block;
import net.minecraft.block.BlockFence;
import net.minecraft.block.BlockPressurePlate.Sensitivity;
import net.minecraft.block.material.MapColor;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.world.IBlockAccess;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;

public class NetherBlocks {
   public static Block acid;
   public static final Block netherite_ore;
   public static final Block netherite_block;
   public static final Block glowstone_torch;
   public static final Block curse_block;
   public static final Block wither_ore;
   public static final Block wither_block;
   public static final Block wither_gem_block;
   public static final Block gold_ore_nether;
   public static final Block soul_tnt;
   public static final Block nether_log;
   public static final Block nether_planks;
   public static final Block nether_stairs;
   public static final Block nether_slab;
   public static final Block nether_leaves;
   public static final Block nether_sapling;
   public static final Block smooth_netherrack;
   public static final Block nether_mushroom;
   public static final Block nether_mushroom_block;
   public static final Block dark_fire;
   public static final BlockAbyssPortal abyss_portal;
   public static final Block darkstone;
   public static final Block dimstone;
   public static final Block dimensional_ore;
   public static final Block smooth_netherrack_stairs;
   public static final Block smooth_netherrack_slab;
   public static final Block obsidian_stairs;
   public static final Block obsidian_slab;
   public static final Block obsidian_fence;
   public static final Block soul_glass;
   public static final Block soul_glass_ghost;
   public static final Block soul_glass_pane;
   public static final Block soul_glass_ghost_pane;
   public static final Block obsidian_fence_gate;
   public static final Block nether_fence;
   public static final Block nether_fence_gate;
   public static final Block nether_brick_fence_gate;
   public static final Block nether_trapdoor;
   public static final Block nether_trapdoor_hidden;
   public static final Block nether_door;
   public static final Block netherrack_chiseled;
   public static final Block nether_pressure_plate;
   public static final Block light_block;
   public static final Block ghost_block;
   public static final Block nether_spikes;
   public static final Block obsidian_smooth;
   public static final Block obsidian_chiseled;
   public static final Block dark_bricks;
   public static final Block nether_crafting_table;
   public static final Block nether_altar;
   public static final Block dark_sand;
   public static final Block wither_ore_darkstone;
   public static final Block netherite_ore_darkstone;
   public static final Block obsidian_bars;
   public static final Block nether_furnace;
   public static final Block lit_nether_furnace;
   public static Fluid fluidAcid;

   public static void init() {
      FluidRegistry.registerFluid(fluidAcid);
      acid = (new BlockAcid(fluidAcid, Material.water)).setBlockTextureName("dextersnether:acid").setBlockName("acid").setHardness(100.0F).setLightOpacity(3).setLightLevel(0.5F);
   }

   public static void register() {
      obsidian_bars.setHarvestLevel("pickaxe", 2);
      String id = "dextersnether";
      ModHelper.registerBlock(gold_ore_nether, id);
      ModHelper.registerBlock(wither_ore, id);
      ModHelper.registerBlock(netherite_ore, id);
      ModHelper.registerBlock(smooth_netherrack, id);
      ModHelper.registerBlock(netherrack_chiseled, id);
      ModHelper.registerBlock(smooth_netherrack_stairs, id);
      ModHelper.registerBlock(smooth_netherrack_slab, id);
      ModHelper.registerBlock(nether_furnace, id);
      ModHelper.registerBlock(lit_nether_furnace, id);
      ModHelper.registerBlock(nether_spikes, id);
      ModHelper.registerBlock(soul_tnt, id);
      ModHelper.registerBlock(soul_glass, id);
      ModHelper.registerBlock(soul_glass_ghost, id);
      ModHelper.registerBlock(soul_glass_pane, id);
      ModHelper.registerBlock(soul_glass_ghost_pane, id);
      ModHelper.registerBlock(nether_sapling, id);
      ModHelper.registerBlock(nether_leaves, id);
      ModHelper.registerBlock(nether_log, id);
      ModHelper.registerBlock(nether_planks, id);
      ModHelper.registerBlock(nether_stairs, id);
      ModHelper.registerBlock(nether_slab, id);
      ModHelper.registerBlock(nether_fence, id);
      ModHelper.registerBlock(nether_fence_gate, id);
      ModHelper.registerBlock(nether_trapdoor, id);
      ModHelper.registerBlock(nether_trapdoor_hidden);
      ModHelper.registerBlock(nether_door, id);
      ModHelper.registerBlock(nether_pressure_plate, id);
      ModHelper.registerBlock(nether_crafting_table, id);
      ModHelper.registerBlock(glowstone_torch, id);
      ModHelper.registerBlock(nether_altar, id);
      ModHelper.registerBlock(netherite_block, id);
      ModHelper.registerBlock(wither_block, id);
      ModHelper.registerBlock(wither_gem_block, id);
      ModHelper.registerBlock(obsidian_smooth, id);
      ModHelper.registerBlock(obsidian_chiseled, id);
      ModHelper.registerBlock(obsidian_stairs, id);
      ModHelper.registerBlock(obsidian_slab, id);
      ModHelper.registerBlock(obsidian_fence, id);
      ModHelper.registerBlock(obsidian_fence_gate, id);
      ModHelper.registerBlock(obsidian_bars, id);
      ModHelper.registerBlock(dark_fire, id);
      ModHelper.registerBlock(dark_bricks, id);
      ModHelper.registerBlock(abyss_portal, id);
      ModHelper.registerBlock(nether_brick_fence_gate, id);
      ModHelper.registerBlock(darkstone, id);
      ModHelper.registerBlock(wither_ore_darkstone, id);
      ModHelper.registerBlock(netherite_ore_darkstone, id);
      ModHelper.registerBlock(dimensional_ore, id);
      ModHelper.registerBlock(dark_sand, id);
      ModHelper.registerBlock(dimstone, id);
      ModHelper.registerBlock(nether_mushroom, id);
      ModHelper.registerBlock(nether_mushroom_block);
      ModHelper.registerBlock(curse_block, id);
      ModHelper.registerBlock(light_block);
      ModHelper.registerBlock(ghost_block);
      ModHelper.registerBlock(acid, id);
   }

   static {
      netherite_ore = (new BlockCustomOre(NetherItems.netherite_nugget, 1, 4, 3, 5, MapColor.netherrackColor)).setHardness(3.0F).setResistance(5.0F).setStepSound(Block.soundTypePiston).setBlockName("netherite_ore").setCreativeTab(DextersNether.tabDextersNether);
      netherite_block = (new BlockCustom(Material.iron, MapColor.ironColor, true)).setHardness(3.8F).setResistance(39.8F).setLightLevel(0.9F).setStepSound(Block.soundTypeMetal).setBlockName("netherite_block").setCreativeTab(DextersNether.tabDextersNether);
      glowstone_torch = (new BlockGlowstoneTorch()).setBlockName("glowstone_torch").setCreativeTab(DextersNether.tabDextersNether);
      curse_block = (new BlockCurse(Material.vine)).setBlockName("curse_block");
      wither_ore = (new BlockCustomOre(NetherItems.wither_dust, 3, 5, 2, 3, MapColor.netherrackColor)).setHardness(3.0F).setResistance(5.0F).setStepSound(Block.soundTypePiston).setBlockName("wither_ore").setCreativeTab(DextersNether.tabDextersNether);
      wither_block = (new BlockWitherBlock(Material.iron, 0)).setBlockName("wither_block").setCreativeTab(DextersNether.tabDextersNether);
      wither_gem_block = (new BlockWitherBlock(Material.iron, 1)).setBlockName("wither_gem_block").setCreativeTab(DextersNether.tabDextersNether);
      gold_ore_nether = (new BlockCustomOre(Items.gold_nugget, 4, 8, 2, 2, MapColor.netherrackColor)).setHardness(3.0F).setResistance(5.0F).setStepSound(Block.soundTypePiston).setBlockName("gold_ore_nether").setCreativeTab(DextersNether.tabDextersNether);
      soul_tnt = (new BlockSoulTNT()).setBlockName("soul_tnt").setCreativeTab(DextersNether.tabDextersNether);
      nether_log = (new BlockNetherLog()).setBlockName("nether_log").setCreativeTab(DextersNether.tabDextersNether);
      nether_planks = (new BlockCustom(Material.wood, MapColor.redColor, false)).setHardness(3.0F).setResistance(16.8F).setStepSound(Block.soundTypeWood).setBlockName("nether_planks").setCreativeTab(DextersNether.tabDextersNether);
      nether_stairs = (new BlockCustomStairs(nether_planks)).setBlockName("nether_stairs").setCreativeTab(DextersNether.tabDextersNether);
      nether_slab = (new BlockCustomSlab(nether_planks)).setHardness(3.0F).setResistance(16.8F).setStepSound(Block.soundTypeWood).setBlockName("nether_slab").setCreativeTab(DextersNether.tabDextersNether);
      nether_leaves = (new BlockNetherLeaves()).setBlockName("nether_leaves").setCreativeTab(DextersNether.tabDextersNether);
      nether_sapling = (new BlockNetherSapling()).setBlockName("nether_sapling").setCreativeTab(DextersNether.tabDextersNether);
      smooth_netherrack = (new BlockCustom(Material.rock, MapColor.netherrackColor, false)).setHardness(1.3F).setResistance(10.0F).setStepSound(Block.soundTypePiston).setBlockName("smooth_netherrack").setCreativeTab(DextersNether.tabDextersNether);
      nether_mushroom = (new BlockNetherMushroom()).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("nether_mushroom").setCreativeTab(DextersNether.tabDextersNether);
      nether_mushroom_block = (new BlockHugeNetherMushroom(Material.wood)).setHardness(0.2F).setStepSound(Block.soundTypeWood).setLightLevel(0.3F).setBlockName("nether_mushroom_block").setBlockTextureName("dextersnether:nether_mushroom");
      dark_fire = (new BlockDarkFire()).setBlockName("dark_fire");
      abyss_portal = (BlockAbyssPortal)(new BlockAbyssPortal()).setBlockName("abyss_portal").setCreativeTab(DextersNether.tabDextersNether);
      darkstone = (new BlockDarkstone()).setBlockName("darkstone").setCreativeTab(DextersNether.tabDextersNether);
      dimstone = (new BlockDimstone(Material.glass)).setHardness(0.3F).setStepSound(Block.soundTypeGlass).setBlockName("dimstone").setLightLevel(0.2F).setCreativeTab(DextersNether.tabDextersNether);
      dimensional_ore = (new BlockCustomOre(NetherItems.dimensional_dust, 2, 4, 3, 5, MapColor.blackColor)).setHardness(3.0F).setResistance(5.0F).setStepSound(Block.soundTypePiston).setBlockName("dimensional_ore").setCreativeTab(DextersNether.tabDextersNether);
      smooth_netherrack_stairs = (new BlockCustomStairs(smooth_netherrack)).setHardness(1.3F).setResistance(10.0F).setStepSound(Block.soundTypePiston).setBlockName("smooth_netherrack_stairs").setCreativeTab(DextersNether.tabDextersNether);
      smooth_netherrack_slab = (new BlockCustomSlab(smooth_netherrack)).setHardness(1.3F).setResistance(10.0F).setStepSound(Block.soundTypePiston).setBlockName("smooth_netherrack_slab").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_stairs = (new BlockCustomStairs(Blocks.obsidian)).setHardness(50.0F).setResistance(2000.0F).setStepSound(Block.soundTypePiston).setBlockName("obsidian_stairs").setCreativeTab(DextersNether.tabDextersNether).setLightOpacity(255);
      obsidian_slab = (new BlockCustomSlab(Blocks.obsidian)).setHardness(50.0F).setResistance(2000.0F).setStepSound(Block.soundTypePiston).setBlockName("obsidian_slab").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_fence = (new BlockFence("obsidian", Material.rock) {
         public boolean canConnectFenceTo(IBlockAccess p_149826_1_, int p_149826_2_, int p_149826_3_, int p_149826_4_) {
            Block block = p_149826_1_.getBlock(p_149826_2_, p_149826_3_, p_149826_4_);
            return block != this && block != NetherBlocks.obsidian_fence_gate ? (block.getMaterial().isOpaque() && block.renderAsNormalBlock() ? block.getMaterial() != Material.gourd : false) : true;
         }
      }).setHardness(50.0F).setResistance(2000.0F).setStepSound(Block.soundTypePiston).setBlockName("obsidian_fence").setCreativeTab(DextersNether.tabDextersNether);
      soul_glass = (new BlockSoulGlass(Material.glass, false, false)).setBlockName("soul_glass").setCreativeTab(DextersNether.tabDextersNether).setHardness(0.4F).setStepSound(Block.soundTypeGlass);
      soul_glass_ghost = (new BlockSoulGlass(Material.glass, false, true)).setBlockName("soul_glass_ghost").setHardness(0.4F).setStepSound(Block.soundTypeGlass);
      soul_glass_pane = (new BlockSoulPane("dextersnether:soul_glass", "dextersnether:soul_glass_pane_top", Material.glass, false, false)).setBlockName("soul_glass_pane").setCreativeTab(DextersNether.tabDextersNether).setHardness(0.4F).setStepSound(Block.soundTypeGlass);
      soul_glass_ghost_pane = (new BlockSoulPane("dextersnether:soul_glass", "dextersnether:soul_glass_pane_top", Material.glass, false, true)).setBlockName("soul_glass_ghost_pane").setHardness(0.4F).setStepSound(Block.soundTypeGlass);
      obsidian_fence_gate = (new BlockHellFenceGate(Material.rock, Blocks.obsidian)).setHardness(50.0F).setResistance(2000.0F).setStepSound(Block.soundTypePiston).setBlockName("obsidian_fence_gate").setBlockTextureName("obsidian").setCreativeTab(DextersNether.tabDextersNether);
      nether_fence = (new BlockFence("dextersnether:nether_planks", Material.rock) {
         public boolean canConnectFenceTo(IBlockAccess p_149826_1_, int p_149826_2_, int p_149826_3_, int p_149826_4_) {
            Block block = p_149826_1_.getBlock(p_149826_2_, p_149826_3_, p_149826_4_);
            return block != this && block != NetherBlocks.nether_fence_gate ? (block.getMaterial().isOpaque() && block.renderAsNormalBlock() ? block.getMaterial() != Material.gourd : false) : true;
         }
      }).setHardness(3.0F).setResistance(16.8F).setStepSound(Block.soundTypeWood).setBlockName("nether_fence").setCreativeTab(DextersNether.tabDextersNether);
      nether_fence_gate = (new BlockHellFenceGate(Material.wood, nether_planks)).setHardness(3.0F).setResistance(16.8F).setStepSound(Block.soundTypeWood).setBlockName("nether_fence_gate").setCreativeTab(DextersNether.tabDextersNether);
      nether_brick_fence_gate = (new BlockHellFenceGate(Material.rock, Blocks.nether_brick)).setHardness(3.0F).setResistance(16.8F).setStepSound(Block.soundTypeWood).setBlockName("nether_brick_fence_gate").setCreativeTab(DextersNether.tabDextersNether);
      nether_trapdoor = (new BlockCustomTrapDoor(Material.wood)).setHardness(3.0F).setResistance(16.8F).setStepSound(Block.soundTypeWood).setBlockName("nether_trapdoor").setCreativeTab(DextersNether.tabDextersNether);
      nether_trapdoor_hidden = (new BlockCustomTrapDoor(Material.wood)).setHardness(3.0F).setResistance(16.8F).setStepSound(Block.soundTypeWood).setBlockName("nether_trapdoor_hidden").setBlockTextureName("dextersnether:nether_planks").setCreativeTab(DextersNether.tabDextersNether);
      nether_door = (new BlockHellDoor(Material.wood)).setHardness(3.0F).setStepSound(Block.soundTypeWood).setBlockName("nether_door");
      netherrack_chiseled = (new BlockCustom(Material.rock, MapColor.netherrackColor, false)).setHardness(1.3F).setResistance(10.0F).setStepSound(Block.soundTypePiston).setBlockName("netherrack_chiseled").setCreativeTab(DextersNether.tabDextersNether);
      nether_pressure_plate = (new BlockHellPressurePlate("dextersnether:nether_planks", Material.wood, Sensitivity.everything)).setHardness(0.5F).setStepSound(Block.soundTypeWood).setBlockName("nether_pressure_plate").setCreativeTab(DextersNether.tabDextersNether);
      light_block = (new BlockGhost(Material.circuits, true)).setLightLevel(1.0F).setBlockName("light_block");
      ghost_block = (new BlockGhost(Material.rock, false)).setBlockName("ghost_block");
      nether_spikes = (new BlockSpikes(Material.rock)).setBlockName("nether_spikes").setCreativeTab(DextersNether.tabDextersNether).setStepSound(Block.soundTypeStone).setHardness(2.0F).setResistance(4.0F);
      obsidian_smooth = (new BlockCustom(Material.rock, MapColor.obsidianColor, false)).setHardness(50.0F).setResistance(2000.0F).setStepSound(Block.soundTypePiston).setBlockName("obsidian_smooth").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_chiseled = (new BlockCustom(Material.rock, MapColor.obsidianColor, false)).setHardness(50.0F).setResistance(2000.0F).setStepSound(Block.soundTypePiston).setBlockName("obsidian_chiseled").setCreativeTab(DextersNether.tabDextersNether);
      dark_bricks = (new BlockCustom(Material.rock, MapColor.obsidianColor, false)).setHardness(56.0F).setResistance(2000.0F).setStepSound(Block.soundTypeMetal).setBlockName("dark_bricks").setCreativeTab(DextersNether.tabDextersNether);
      nether_crafting_table = (new BlockNetherCraftingTable()).setBlockName("nether_crafting_table").setCreativeTab(DextersNether.tabDextersNether).setStepSound(Block.soundTypeWood).setHardness(3.0F).setResistance(16.8F);
      nether_altar = (new BlockNetherAltar()).setBlockName("nether_altar").setCreativeTab(DextersNether.tabDextersNether).setHardness(8.0F).setResistance(2000.0F).setStepSound(Block.soundTypeMetal);
      dark_sand = (new BlockDarkSand()).setHardness(0.6F).setResistance(4.0F).setStepSound(Block.soundTypeMetal).setBlockName("dark_sand").setCreativeTab(DextersNether.tabDextersNether);
      wither_ore_darkstone = (new BlockCustomOre(NetherItems.wither_dust, 3, 5, 2, 3, MapColor.blackColor)).setHardness(3.0F).setResistance(40.0F).setStepSound(Block.soundTypePiston).setBlockName("wither_ore_darkstone").setCreativeTab(DextersNether.tabDextersNether);
      netherite_ore_darkstone = (new BlockCustomOre(NetherItems.netherite_nugget, 1, 4, 3, 5, MapColor.blackColor)).setHardness(3.0F).setResistance(40.0F).setStepSound(Block.soundTypePiston).setBlockName("netherite_ore_darkstone").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_bars = (new BlockCustomPane("dextersnether:obsidian_bars", "dextersnether:obsidian_bars", Material.iron, true)).setHardness(8.0F).setResistance(50.0F).setStepSound(Block.soundTypeMetal).setBlockName("obsidian_bars").setCreativeTab(DextersNether.tabDextersNether);
      nether_furnace = (new BlockNetherFurnace(false)).setBlockName("nether_furnace").setCreativeTab(DextersNether.tabDextersNether).setHardness(3.5F).setStepSound(Block.soundTypePiston);
      lit_nether_furnace = (new BlockNetherFurnace(true)).setBlockName("lit_nether_furnace").setHardness(3.5F).setStepSound(Block.soundTypePiston);
      fluidAcid = (new Fluid("fluidAcid")).setUnlocalizedName("fluidAcid");
   }
}
