package com.superdextor.dextersnether.init;

import com.superdextor.dextersnether.DextersNether;
import com.superdextor.dextersnether.items.ItemAmulet;
import com.superdextor.dextersnether.items.ItemGlowstoneArmor;
import com.superdextor.dextersnether.items.ItemGlowstoneSword;
import com.superdextor.dextersnether.items.ItemGoldenBucket;
import com.superdextor.dextersnether.items.ItemNetherBow;
import com.superdextor.dextersnether.items.ItemNetherStaff;
import com.superdextor.dextersnether.items.ItemNetheriteArmor;
import com.superdextor.dextersnether.items.ItemQuartzArmor;
import com.superdextor.dextersnether.items.ItemQuartzSword;
import com.superdextor.dextersnether.items.ItemScythe;
import com.superdextor.dextersnether.items.ItemWitherApple;
import com.superdextor.dextersnether.items.ItemWitherArmor;
import com.superdextor.dextersnether.items.ItemWitherDust;
import com.superdextor.dextersnether.items.ItemWormHole;
import com.superdextor.thinkbigcore.ModHelper;
import com.superdextor.thinkbigcore.items.ItemBlockPlacer;
import com.superdextor.thinkbigcore.items.ItemCustomArmor;
import com.superdextor.thinkbigcore.items.ItemCustomAxe;
import com.superdextor.thinkbigcore.items.ItemCustomDoor;
import com.superdextor.thinkbigcore.items.ItemCustomPickaxe;
import com.superdextor.thinkbigcore.items.ItemCustomRecord;
import com.superdextor.thinkbigcore.items.ItemCustomShovel;
import com.superdextor.thinkbigcore.items.ItemCustomSword;
import net.minecraft.item.Item;
import net.minecraft.item.ItemFireball;
import net.minecraft.item.ItemFood;
import net.minecraft.item.ItemHoe;
import net.minecraft.item.ItemShears;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraft.potion.Potion;
import net.minecraft.potion.PotionEffect;
import net.minecraft.potion.PotionHelper;
import net.minecraftforge.common.util.EnumHelper;

public class NetherItems {
   public static final ToolMaterial NetherrackToolMaterial = EnumHelper.addToolMaterial("NetherrackToolMaterial", 1, 97, 6.0F, 1.0F, 7);
   public static final ArmorMaterial NetherrackArmorMaterial = EnumHelper.addArmorMaterial("NetherrackArmorMaterial", 9, new int[]{1, 4, 2, 1}, 13);
   public static final ToolMaterial QuartzToolMaterial = EnumHelper.addToolMaterial("QuartzToolMaterial", 2, 168, 6.0F, 2.0F, 20);
   public static final ArmorMaterial QuartzArmorMaterial = EnumHelper.addArmorMaterial("QuartzArmorMaterial", 12, new int[]{2, 5, 3, 1}, 30);
   public static final ToolMaterial GlowstoneToolMaterial = EnumHelper.addToolMaterial("GlowstoneToolMaterial", 1, 48, 12.0F, 3.0F, 9);
   public static final ArmorMaterial GlowstoneArmorMaterial = EnumHelper.addArmorMaterial("GlowstoneArmorMaterial", 6, new int[]{2, 4, 3, 1}, 9);
   public static final ToolMaterial ObsidianToolMaterial = EnumHelper.addToolMaterial("ObsidianToolMaterial", 3, 1875, 6.5F, 2.0F, 7);
   public static final ArmorMaterial ObsidianArmorMaterial = EnumHelper.addArmorMaterial("ObsidianArmorMaterial", 37, new int[]{4, 8, 7, 3}, 7);
   public static final ToolMaterial WitherToolMaterial = EnumHelper.addToolMaterial("WitherToolMaterial", 3, 1754, 9.0F, 4.0F, 10);
   public static final ArmorMaterial WitherArmorMaterial = EnumHelper.addArmorMaterial("WitherArmorMaterial", 36, new int[]{3, 8, 6, 3}, 10);
   public static final ToolMaterial NetheriteToolMaterial = EnumHelper.addToolMaterial("NetheriteToolMaterial", 4, 2456, 13.0F, 5.0F, 20);
   public static final ArmorMaterial NetheriteArmorMaterial = EnumHelper.addArmorMaterial("NetheriteArmorMaterial", 39, new int[]{4, 8, 6, 3}, 20);
   public static final Item netherrack_sword;
   public static final Item netherrack_axe;
   public static final Item netherrack_pickaxe;
   public static final Item netherrack_shovel;
   public static final Item netherrack_hoe;
   public static final Item netherite_sword;
   public static final Item netherite_axe;
   public static final Item netherite_pickaxe;
   public static final Item netherite_shovel;
   public static final Item netherite_hoe;
   public static final Item obsidian_sword;
   public static final Item obsidian_axe;
   public static final Item obsidian_pickaxe;
   public static final Item obsidian_shovel;
   public static final Item obsidian_hoe;
   public static final Item wither_sword;
   public static final Item wither_axe;
   public static final Item wither_pickaxe;
   public static final Item wither_shovel;
   public static final Item wither_hoe;
   public static final Item glowstone_sword;
   public static final Item glowstone_axe;
   public static final Item glowstone_pickaxe;
   public static final Item glowstone_shovel;
   public static final Item glowstone_hoe;
   public static final Item quartz_sword;
   public static final Item quartz_axe;
   public static final Item quartz_pickaxe;
   public static final Item quartz_shovel;
   public static final Item quartz_hoe;
   public static final Item flame_staff;
   public static final Item scythe;
   public static final Item wither_staff;
   public static final Item quartz_arrow;
   public static final Item quartz_bow;
   public static final Item glowstone_arrow;
   public static final Item glowstone_bow;
   public static final Item obsidian_arrow;
   public static final Item obsidian_bow;
   public static final Item wither_arrow;
   public static final Item wither_bow;
   public static final Item netherite_arrow;
   public static final Item netherite_bow;
   public static final Item netherrack_helmet;
   public static final Item netherrack_chestplate;
   public static final Item netherrack_leggings;
   public static final Item netherrack_boots;
   public static final Item netherite_helmet;
   public static final Item netherite_chestplate;
   public static final Item netherite_leggings;
   public static final Item netherite_boots;
   public static final Item obsidian_helmet;
   public static final Item obsidian_chestplate;
   public static final Item obsidian_leggings;
   public static final Item obsidian_boots;
   public static final Item wither_helmet;
   public static final Item wither_chestplate;
   public static final Item wither_leggings;
   public static final Item wither_boots;
   public static final Item glowstone_helmet;
   public static final Item glowstone_chestplate;
   public static final Item glowstone_leggings;
   public static final Item glowstone_boots;
   public static final Item quartz_helmet;
   public static final Item quartz_chestplate;
   public static final Item quartz_leggings;
   public static final Item quartz_boots;
   public static final Item quartz_stick;
   public static final Item netherite_nugget;
   public static final Item netherite_ingot;
   public static final Item flameball;
   public static final Item obsidian_nugget;
   public static final Item obsidian_chunk;
   public static final Item obsidian_ingot;
   public static final Item wither_dust;
   public static final Item wither_gem;
   public static final Item quartz_ingot;
   public static final Item flame_string;
   public static final Item golden_bucket_empty;
   public static final Item golden_bucket_lava;
   public static final Item golden_bucket_water;
   public static final Item golden_bucket_acid;
   public static final Item cooked_flesh;
   public static final Item nether_disc;
   public static final Item abyss_disc;
   public static final Item golden_shears;
   public static final Item fired_nether_mushroom;
   public static final Item darkcore;
   public static final Item dimstone_dust;
   public static final Item ectoplasm;
   public static final Item dimensional_dust;
   public static final Item pocket_worm_hole;
   public static Item nether_door_item;
   public static Item hidden_light;
   public static Item hidden_block;
   public static final Item flame;
   public static final Item dark_brick;
   public static final Item avis_wing;
   public static final Item wither_apple;
   public static final Item amulet;
   public static final Item infernal_rod;
   public static final Item infernal_powder;

   public static void register() {
      hidden_light = (new ItemBlockPlacer(NetherBlocks.light_block, "random.fizz")).setUnlocalizedName("hidden_light").setCreativeTab(DextersNether.tabDextersNether);
      hidden_block = (new ItemBlockPlacer(NetherBlocks.ghost_block, "dig.wood")).setUnlocalizedName("hidden_block").setCreativeTab(DextersNether.tabDextersNether);
      nether_door_item = (new ItemCustomDoor(NetherBlocks.nether_door)).setUnlocalizedName("nether_door_item").setCreativeTab(DextersNether.tabDextersNether).setTextureName("dextersnether:nether_door");
      String id = "dextersnether";
      ModHelper.registerItem(fired_nether_mushroom, id);
      ModHelper.registerItem(cooked_flesh, id);
      ModHelper.registerItem(wither_apple, id);
      ModHelper.registerItem(scythe, id);
      ModHelper.registerItem(golden_bucket_empty, id);
      ModHelper.registerItem(golden_bucket_lava, id);
      ModHelper.registerItem(golden_bucket_water, id);
      ModHelper.registerItem(golden_bucket_acid, id);
      ModHelper.registerItem(golden_shears, id);
      ModHelper.registerItem(flame_staff, id);
      ModHelper.registerItem(wither_staff, id);
      ModHelper.registerItem(pocket_worm_hole, id);
      ModHelper.registerItem(amulet, id);
      ModHelper.registerItem(netherrack_sword, id);
      ModHelper.registerItem(netherrack_axe, id);
      ModHelper.registerItem(netherrack_pickaxe, id);
      ModHelper.registerItem(netherrack_shovel, id);
      ModHelper.registerItem(netherrack_hoe, id);
      ModHelper.registerItem(netherrack_helmet, id);
      ModHelper.registerItem(netherrack_chestplate, id);
      ModHelper.registerItem(netherrack_leggings, id);
      ModHelper.registerItem(netherrack_boots, id);
      ModHelper.registerItem(quartz_sword, id);
      ModHelper.registerItem(quartz_axe, id);
      ModHelper.registerItem(quartz_pickaxe, id);
      ModHelper.registerItem(quartz_shovel, id);
      ModHelper.registerItem(quartz_hoe, id);
      ModHelper.registerItem(quartz_helmet, id);
      ModHelper.registerItem(quartz_chestplate, id);
      ModHelper.registerItem(quartz_leggings, id);
      ModHelper.registerItem(quartz_boots, id);
      ModHelper.registerItem(glowstone_sword, id);
      ModHelper.registerItem(glowstone_axe, id);
      ModHelper.registerItem(glowstone_pickaxe, id);
      ModHelper.registerItem(glowstone_shovel, id);
      ModHelper.registerItem(glowstone_hoe, id);
      ModHelper.registerItem(glowstone_helmet, id);
      ModHelper.registerItem(glowstone_chestplate, id);
      ModHelper.registerItem(glowstone_leggings, id);
      ModHelper.registerItem(glowstone_boots, id);
      ModHelper.registerItem(obsidian_sword, id);
      ModHelper.registerItem(obsidian_axe, id);
      ModHelper.registerItem(obsidian_pickaxe, id);
      ModHelper.registerItem(obsidian_shovel, id);
      ModHelper.registerItem(obsidian_hoe, id);
      ModHelper.registerItem(obsidian_helmet, id);
      ModHelper.registerItem(obsidian_chestplate, id);
      ModHelper.registerItem(obsidian_leggings, id);
      ModHelper.registerItem(obsidian_boots, id);
      ModHelper.registerItem(wither_sword, id);
      ModHelper.registerItem(wither_axe, id);
      ModHelper.registerItem(wither_pickaxe, id);
      ModHelper.registerItem(wither_shovel, id);
      ModHelper.registerItem(wither_hoe, id);
      ModHelper.registerItem(wither_helmet, id);
      ModHelper.registerItem(wither_chestplate, id);
      ModHelper.registerItem(wither_leggings, id);
      ModHelper.registerItem(wither_boots, id);
      ModHelper.registerItem(netherite_sword, id);
      ModHelper.registerItem(netherite_axe, id);
      ModHelper.registerItem(netherite_pickaxe, id);
      ModHelper.registerItem(netherite_shovel, id);
      ModHelper.registerItem(netherite_hoe, id);
      ModHelper.registerItem(netherite_helmet, id);
      ModHelper.registerItem(netherite_chestplate, id);
      ModHelper.registerItem(netherite_leggings, id);
      ModHelper.registerItem(netherite_boots, id);
      ModHelper.registerItem(nether_disc, id);
      ModHelper.registerItem(abyss_disc, id);
      ModHelper.registerItem(hidden_light, id);
      ModHelper.registerItem(hidden_block, id);
      ModHelper.registerItem(quartz_bow, id);
      ModHelper.registerItem(glowstone_bow, id);
      ModHelper.registerItem(obsidian_bow, id);
      ModHelper.registerItem(wither_bow, id);
      ModHelper.registerItem(netherite_bow, id);
      ModHelper.registerItem(infernal_rod, id);
      ModHelper.registerItem(infernal_powder, id);
      ModHelper.registerItem(flameball, id);
      ModHelper.registerItem(nether_door_item);
      ModHelper.registerItem(quartz_arrow, id);
      ModHelper.registerItem(glowstone_arrow, id);
      ModHelper.registerItem(obsidian_arrow, id);
      ModHelper.registerItem(wither_arrow, id);
      ModHelper.registerItem(netherite_arrow, id);
      ModHelper.registerItem(flame_string, id);
      ModHelper.registerItem(quartz_stick, id);
      ModHelper.registerItem(quartz_ingot, id);
      ModHelper.registerItem(netherite_nugget, id);
      ModHelper.registerItem(netherite_ingot, id);
      ModHelper.registerItem(ectoplasm, id);
      ModHelper.registerItem(dimensional_dust, id);
      ModHelper.registerItem(avis_wing, id);
      ModHelper.registerItem(dark_brick, id);
      ModHelper.registerItem(dimstone_dust, id);
      ModHelper.registerItem(wither_dust, id);
      ModHelper.registerItem(wither_gem, id);
      ModHelper.registerItem(obsidian_nugget, id);
      ModHelper.registerItem(obsidian_chunk, id);
      ModHelper.registerItem(obsidian_ingot, id);
      ModHelper.registerItem(darkcore, id);
      ModHelper.registerItem(flame);
   }

   static {
      netherrack_sword = (new ItemCustomSword(NetherrackToolMaterial)).setUnlocalizedName("netherrack_sword").setCreativeTab(DextersNether.tabDextersNether);
      netherrack_axe = (new ItemCustomAxe(NetherrackToolMaterial)).setUnlocalizedName("netherrack_axe").setCreativeTab(DextersNether.tabDextersNether);
      netherrack_pickaxe = (new ItemCustomPickaxe(NetherrackToolMaterial)).setUnlocalizedName("netherrack_pickaxe").setCreativeTab(DextersNether.tabDextersNether);
      netherrack_shovel = (new ItemCustomShovel(NetherrackToolMaterial)).setUnlocalizedName("netherrack_shovel").setCreativeTab(DextersNether.tabDextersNether);
      netherrack_hoe = (new ItemHoe(NetherrackToolMaterial)).setUnlocalizedName("netherrack_hoe").setCreativeTab(DextersNether.tabDextersNether);
      netherite_sword = (new ItemCustomSword(NetheriteToolMaterial, new PotionEffect(Potion.blindness.id, 240, 0))).setUnlocalizedName("netherite_sword").setCreativeTab(DextersNether.tabDextersNether);
      netherite_axe = (new ItemCustomAxe(NetheriteToolMaterial, new PotionEffect(Potion.blindness.id, 240, 0))).setUnlocalizedName("netherite_axe").setCreativeTab(DextersNether.tabDextersNether);
      netherite_pickaxe = (new ItemCustomPickaxe(NetheriteToolMaterial, new PotionEffect(Potion.blindness.id, 240, 0))).setUnlocalizedName("netherite_pickaxe").setCreativeTab(DextersNether.tabDextersNether);
      netherite_shovel = (new ItemCustomShovel(NetheriteToolMaterial, new PotionEffect(Potion.blindness.id, 240, 0))).setUnlocalizedName("netherite_shovel").setCreativeTab(DextersNether.tabDextersNether);
      netherite_hoe = (new ItemHoe(NetheriteToolMaterial)).setUnlocalizedName("netherite_hoe").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_sword = (new ItemCustomSword(ObsidianToolMaterial)).setUnlocalizedName("obsidian_sword").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_axe = (new ItemCustomAxe(ObsidianToolMaterial)).setUnlocalizedName("obsidian_axe").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_pickaxe = (new ItemCustomPickaxe(ObsidianToolMaterial)).setUnlocalizedName("obsidian_pickaxe").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_shovel = (new ItemCustomShovel(ObsidianToolMaterial)).setUnlocalizedName("obsidian_shovel").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_hoe = (new ItemHoe(ObsidianToolMaterial)).setUnlocalizedName("obsidian_hoe").setCreativeTab(DextersNether.tabDextersNether);
      wither_sword = (new ItemCustomSword(WitherToolMaterial, new PotionEffect(Potion.wither.id, 120))).setUnlocalizedName("wither_sword").setCreativeTab(DextersNether.tabDextersNether);
      wither_axe = (new ItemCustomAxe(WitherToolMaterial, new PotionEffect(Potion.wither.id, 120))).setUnlocalizedName("wither_axe").setCreativeTab(DextersNether.tabDextersNether);
      wither_pickaxe = (new ItemCustomPickaxe(WitherToolMaterial, new PotionEffect(Potion.wither.id, 120))).setUnlocalizedName("wither_pickaxe").setCreativeTab(DextersNether.tabDextersNether);
      wither_shovel = (new ItemCustomShovel(WitherToolMaterial, new PotionEffect(Potion.wither.id, 120))).setUnlocalizedName("wither_shovel").setCreativeTab(DextersNether.tabDextersNether);
      wither_hoe = (new ItemHoe(WitherToolMaterial)).setUnlocalizedName("wither_hoe").setCreativeTab(DextersNether.tabDextersNether);
      glowstone_sword = (new ItemGlowstoneSword(GlowstoneToolMaterial)).setUnlocalizedName("glowstone_sword").setCreativeTab(DextersNether.tabDextersNether);
      glowstone_axe = (new ItemCustomAxe(GlowstoneToolMaterial)).setUnlocalizedName("glowstone_axe").setCreativeTab(DextersNether.tabDextersNether);
      glowstone_pickaxe = (new ItemCustomPickaxe(GlowstoneToolMaterial)).setUnlocalizedName("glowstone_pickaxe").setCreativeTab(DextersNether.tabDextersNether);
      glowstone_shovel = (new ItemCustomShovel(GlowstoneToolMaterial)).setUnlocalizedName("glowstone_shovel").setCreativeTab(DextersNether.tabDextersNether);
      glowstone_hoe = (new ItemHoe(GlowstoneToolMaterial)).setUnlocalizedName("glowstone_hoe").setCreativeTab(DextersNether.tabDextersNether);
      quartz_sword = (new ItemQuartzSword(QuartzToolMaterial)).setUnlocalizedName("quartz_sword").setCreativeTab(DextersNether.tabDextersNether);
      quartz_axe = (new ItemCustomAxe(QuartzToolMaterial)).setUnlocalizedName("quartz_axe").setCreativeTab(DextersNether.tabDextersNether);
      quartz_pickaxe = (new ItemCustomPickaxe(QuartzToolMaterial)).setUnlocalizedName("quartz_pickaxe").setCreativeTab(DextersNether.tabDextersNether);
      quartz_shovel = (new ItemCustomShovel(QuartzToolMaterial)).setUnlocalizedName("quartz_shovel").setCreativeTab(DextersNether.tabDextersNether);
      quartz_hoe = (new ItemHoe(QuartzToolMaterial)).setUnlocalizedName("quartz_hoe").setCreativeTab(DextersNether.tabDextersNether);
      flame_staff = (new ItemNetherStaff(0)).setUnlocalizedName("flame_staff").setCreativeTab(DextersNether.tabDextersNether);
      scythe = (new ItemScythe()).setUnlocalizedName("scythe").setTextureName("dextersnether:scythe").setCreativeTab(DextersNether.tabDextersNether);
      wither_staff = (new ItemNetherStaff(1)).setUnlocalizedName("wither_staff").setCreativeTab(DextersNether.tabDextersNether);
      quartz_arrow = (new Item()).setUnlocalizedName("quartz_arrow").setCreativeTab(DextersNether.tabDextersNether);
      quartz_bow = (new ItemNetherBow("dextersnether:quartz_bow", 168, quartz_arrow, 6, 0.7D, 1.1F, 12, 1.0F, 0)).setUnlocalizedName("quartz_bow").setCreativeTab(DextersNether.tabDextersNether);
      glowstone_arrow = (new Item()).setUnlocalizedName("glowstone_arrow").setCreativeTab(DextersNether.tabDextersNether);
      glowstone_bow = (new ItemNetherBow("dextersnether:glowstone_bow", 48, glowstone_arrow, -1, 1.1D, 0.6F, 21, 0.8F, 1)).setUnlocalizedName("glowstone_bow").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_arrow = (new Item()).setUnlocalizedName("obsidian_arrow").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_bow = (new ItemNetherBow("dextersnether:obsidian_bow", 1875, obsidian_arrow, -12, 4.0D, 0.4F, 40, 0.6F, 2)).setUnlocalizedName("obsidian_bow").setCreativeTab(DextersNether.tabDextersNether);
      wither_arrow = (new Item()).setUnlocalizedName("wither_arrow").setCreativeTab(DextersNether.tabDextersNether);
      wither_bow = (new ItemNetherBow("dextersnether:wither_bow", 1754, wither_arrow, 0, 1.3D, 1.0F, 20, 1.2F, 3)).setUnlocalizedName("wither_bow").setCreativeTab(DextersNether.tabDextersNether);
      netherite_arrow = (new Item()).setUnlocalizedName("netherite_arrow").setCreativeTab(DextersNether.tabDextersNether);
      netherite_bow = (new ItemNetherBow("dextersnether:netherite_bow", 2456, netherite_arrow, 4, 1.5D, 1.2F, 16, 1.4F, 4)).setUnlocalizedName("netherite_bow").setCreativeTab(DextersNether.tabDextersNether);
      netherrack_helmet = (new ItemCustomArmor(NetherrackArmorMaterial, 0, 0, "dextersnether:textures/models/armor/netherrack")).setUnlocalizedName("netherrack_helmet").setCreativeTab(DextersNether.tabDextersNether);
      netherrack_chestplate = (new ItemCustomArmor(NetherrackArmorMaterial, 0, 1, "dextersnether:textures/models/armor/netherrack")).setUnlocalizedName("netherrack_chestplate").setCreativeTab(DextersNether.tabDextersNether);
      netherrack_leggings = (new ItemCustomArmor(NetherrackArmorMaterial, 0, 2, "dextersnether:textures/models/armor/netherrack")).setUnlocalizedName("netherrack_leggings").setCreativeTab(DextersNether.tabDextersNether);
      netherrack_boots = (new ItemCustomArmor(NetherrackArmorMaterial, 0, 3, "dextersnether:textures/models/armor/netherrack")).setUnlocalizedName("netherrack_boots").setCreativeTab(DextersNether.tabDextersNether);
      netherite_helmet = (new ItemNetheriteArmor(NetheriteArmorMaterial, 0, 0)).setUnlocalizedName("netherite_helmet").setCreativeTab(DextersNether.tabDextersNether);
      netherite_chestplate = (new ItemNetheriteArmor(NetheriteArmorMaterial, 0, 1)).setUnlocalizedName("netherite_chestplate").setCreativeTab(DextersNether.tabDextersNether);
      netherite_leggings = (new ItemNetheriteArmor(NetheriteArmorMaterial, 0, 2)).setUnlocalizedName("netherite_leggings").setCreativeTab(DextersNether.tabDextersNether);
      netherite_boots = (new ItemNetheriteArmor(NetheriteArmorMaterial, 0, 3)).setUnlocalizedName("netherite_boots").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_helmet = (new ItemCustomArmor(ObsidianArmorMaterial, 0, 0, "dextersnether:textures/models/armor/obsidian", new PotionEffect(Potion.moveSlowdown.id, 10, 0))).setUnlocalizedName("obsidian_helmet").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_chestplate = (new ItemCustomArmor(ObsidianArmorMaterial, 0, 1, "dextersnether:textures/models/armor/obsidian", new PotionEffect(Potion.moveSlowdown.id, 10, 0))).setUnlocalizedName("obsidian_chestplate").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_leggings = (new ItemCustomArmor(ObsidianArmorMaterial, 0, 2, "dextersnether:textures/models/armor/obsidian", new PotionEffect(Potion.moveSlowdown.id, 10, 0))).setUnlocalizedName("obsidian_leggings").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_boots = (new ItemCustomArmor(ObsidianArmorMaterial, 0, 3, "dextersnether:textures/models/armor/obsidian", new PotionEffect(Potion.moveSlowdown.id, 10, 0))).setUnlocalizedName("obsidian_boots").setCreativeTab(DextersNether.tabDextersNether);
      wither_helmet = (new ItemWitherArmor(WitherArmorMaterial, 0, 0)).setUnlocalizedName("wither_helmet").setCreativeTab(DextersNether.tabDextersNether);
      wither_chestplate = (new ItemWitherArmor(WitherArmorMaterial, 0, 1)).setUnlocalizedName("wither_chestplate").setCreativeTab(DextersNether.tabDextersNether);
      wither_leggings = (new ItemWitherArmor(WitherArmorMaterial, 0, 2)).setUnlocalizedName("wither_leggings").setCreativeTab(DextersNether.tabDextersNether);
      wither_boots = (new ItemWitherArmor(WitherArmorMaterial, 0, 3)).setUnlocalizedName("wither_boots").setCreativeTab(DextersNether.tabDextersNether);
      glowstone_helmet = (new ItemGlowstoneArmor(GlowstoneArmorMaterial, 0, 0)).setUnlocalizedName("glowstone_helmet").setCreativeTab(DextersNether.tabDextersNether);
      glowstone_chestplate = (new ItemGlowstoneArmor(GlowstoneArmorMaterial, 0, 1)).setUnlocalizedName("glowstone_chestplate").setCreativeTab(DextersNether.tabDextersNether);
      glowstone_leggings = (new ItemGlowstoneArmor(GlowstoneArmorMaterial, 0, 2)).setUnlocalizedName("glowstone_leggings").setCreativeTab(DextersNether.tabDextersNether);
      glowstone_boots = (new ItemGlowstoneArmor(GlowstoneArmorMaterial, 0, 3)).setUnlocalizedName("glowstone_boots").setCreativeTab(DextersNether.tabDextersNether);
      quartz_helmet = (new ItemQuartzArmor(QuartzArmorMaterial, 0, 0)).setUnlocalizedName("quartz_helmet").setCreativeTab(DextersNether.tabDextersNether);
      quartz_chestplate = (new ItemQuartzArmor(QuartzArmorMaterial, 0, 1)).setUnlocalizedName("quartz_chestplate").setCreativeTab(DextersNether.tabDextersNether);
      quartz_leggings = (new ItemQuartzArmor(QuartzArmorMaterial, 0, 2)).setUnlocalizedName("quartz_leggings").setCreativeTab(DextersNether.tabDextersNether);
      quartz_boots = (new ItemQuartzArmor(QuartzArmorMaterial, 0, 3)).setUnlocalizedName("quartz_boots").setCreativeTab(DextersNether.tabDextersNether);
      quartz_stick = (new Item()).setUnlocalizedName("quartz_stick").setFull3D().setCreativeTab(DextersNether.tabDextersNether);
      netherite_nugget = (new Item()).setUnlocalizedName("netherite_nugget").setCreativeTab(DextersNether.tabDextersNether);
      netherite_ingot = (new Item()).setUnlocalizedName("netherite_ingot").setCreativeTab(DextersNether.tabDextersNether);
      flameball = (new ItemFireball()).setUnlocalizedName("flameball").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_nugget = (new Item()).setUnlocalizedName("obsidian_nugget").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_chunk = (new Item()).setUnlocalizedName("obsidian_chunk").setCreativeTab(DextersNether.tabDextersNether);
      obsidian_ingot = (new Item()).setUnlocalizedName("obsidian_ingot").setCreativeTab(DextersNether.tabDextersNether);
      wither_dust = (new ItemWitherDust()).setUnlocalizedName("wither_dust").setCreativeTab(DextersNether.tabDextersNether);
      wither_gem = (new Item()).setUnlocalizedName("wither_gem").setCreativeTab(DextersNether.tabDextersNether);
      quartz_ingot = (new Item()).setUnlocalizedName("quartz_ingot").setCreativeTab(DextersNether.tabDextersNether);
      flame_string = (new Item()).setUnlocalizedName("flame_string").setCreativeTab(DextersNether.tabDextersNether);
      golden_bucket_empty = (new ItemGoldenBucket(0)).setUnlocalizedName("golden_bucket_empty").setCreativeTab(DextersNether.tabDextersNether).setMaxStackSize(24);
      golden_bucket_lava = (new ItemGoldenBucket(1)).setUnlocalizedName("golden_bucket_lava").setCreativeTab(DextersNether.tabDextersNether).setContainerItem(golden_bucket_empty);
      golden_bucket_water = (new ItemGoldenBucket(2)).setUnlocalizedName("golden_bucket_water").setCreativeTab(DextersNether.tabDextersNether).setContainerItem(golden_bucket_empty);
      golden_bucket_acid = (new ItemGoldenBucket(3)).setUnlocalizedName("golden_bucket_acid").setCreativeTab(DextersNether.tabDextersNether).setContainerItem(golden_bucket_empty);
      cooked_flesh = (new ItemFood(4, false)).setUnlocalizedName("cooked_flesh").setCreativeTab(DextersNether.tabDextersNether);
      nether_disc = (new ItemCustomRecord("nether", "dextersnether")).setUnlocalizedName("nether_disc").setCreativeTab(DextersNether.tabDextersNether);
      abyss_disc = (new ItemCustomRecord("abyss", "dextersnether")).setUnlocalizedName("abyss_disc").setCreativeTab(DextersNether.tabDextersNether);
      golden_shears = (new ItemShears()).setUnlocalizedName("golden_shears").setMaxDamage(300).setMaxStackSize(2).setCreativeTab(DextersNether.tabDextersNether);
      fired_nether_mushroom = (new ItemFood(5, 0.5F, false)).setPotionEffect(Potion.fireResistance.id, 60, 0, 1.0F).setAlwaysEdible().setUnlocalizedName("fired_nether_mushroom").setCreativeTab(DextersNether.tabDextersNether);
      darkcore = (new Item()).setUnlocalizedName("item");
      dimstone_dust = (new Item()).setUnlocalizedName("dimstone_dust").setCreativeTab(DextersNether.tabDextersNether).setPotionEffect(PotionHelper.redstoneEffect);
      ectoplasm = (new Item()).setUnlocalizedName("ectoplasm").setCreativeTab(DextersNether.tabDextersNether);
      dimensional_dust = (new Item()).setUnlocalizedName("dimensional_dust").setCreativeTab(DextersNether.tabDextersNether);
      pocket_worm_hole = (new ItemWormHole()).setUnlocalizedName("pocket_worm_hole").setCreativeTab(DextersNether.tabDextersNether);
      flame = (new Item()).setUnlocalizedName("flame").setTextureName("dextersnether:flame");
      dark_brick = (new Item()).setUnlocalizedName("dark_brick").setCreativeTab(DextersNether.tabDextersNether);
      avis_wing = (new Item()).setUnlocalizedName("avis_wing").setCreativeTab(DextersNether.tabDextersNether);
      wither_apple = (new ItemWitherApple()).setUnlocalizedName("wither_apple").setCreativeTab(DextersNether.tabDextersNether);
      amulet = (new ItemAmulet()).setUnlocalizedName("amulet").setCreativeTab(DextersNether.tabDextersNether);
      infernal_rod = (new Item()).setUnlocalizedName("infernal_rod").setTextureName("dextersnether:infernal_rod").setCreativeTab(DextersNether.tabDextersNether).setFull3D();
      infernal_powder = (new Item()).setUnlocalizedName("infernal_powder").setTextureName("dextersnether:infernal_powder").setCreativeTab(DextersNether.tabDextersNether).setPotionEffect(PotionHelper.magmaCreamEffect);
   }
}
